// <auto-generated />
using Envoycan_Application.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Envoycan_Application.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Envoycan_Application.Models.Services+ACRepair", b =>
                {
                    b.Property<int>("ACRepairID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ACRepairID"));

                    b.Property<string>("ACRepairName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ACRepairID");

                    b.ToTable("ACRepair", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+Carpenter", b =>
                {
                    b.Property<int>("CarpenterServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarpenterServiceID"));

                    b.Property<string>("CarpenterServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarpenterServiceID");

                    b.ToTable("Carpenter", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+HouseCleaning", b =>
                {
                    b.Property<int>("HouseCleaningID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseCleaningID"));

                    b.Property<string>("HouseCleaningName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HouseCleaningID");

                    b.ToTable("HouseCleaning", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+Painter", b =>
                {
                    b.Property<int>("PainterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PainterID"));

                    b.Property<string>("PainterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PainterID");

                    b.ToTable("Painter", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+PestControl", b =>
                {
                    b.Property<int>("PestControlID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PestControlID"));

                    b.Property<string>("PestControlName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PestControlID");

                    b.ToTable("PestControl", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+Plumber", b =>
                {
                    b.Property<int>("PlumberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlumberID"));

                    b.Property<string>("PlumberName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlumberID");

                    b.ToTable("Plumber", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+Salon", b =>
                {
                    b.Property<int>("SalonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalonID"));

                    b.Property<string>("SalonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalonID");

                    b.ToTable("Salon", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.Services+SmartHome", b =>
                {
                    b.Property<int>("SmartHomeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmartHomeID"));

                    b.Property<string>("SmartHomeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SmartHomeID");

                    b.ToTable("SmartHome", (string)null);
                });

            modelBuilder.Entity("Envoycan_Application.Models.UserRegistration_Model", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User_registration");
                });
#pragma warning restore 612, 618
        }
    }
}
